#include<hapi/mpsterm.hpp>
#include<hapi/mpsend.hpp>
#include<hapi/mpssnd.hpp>
#include<hapi/mpssndtype.hpp>
#include<hapi/mpsrcv.hpp>
#include<hapi/mpsrcvtype.hpp>
#include<hapi/mpsselect.hpp>
#include<hapi/mpsbranch.hpp>
#include<hapi/mpscond.hpp>
#include<hapi/mpsnu.hpp>
#include<hapi/mpslink.hpp>
#include<hapi/mpsnew.hpp>
#include<hapi/mpspar.hpp>
#include<hapi/mpsdef.hpp>
#include<hapi/mpscall.hpp>
#include<hapi/mpssync.hpp>
#include<hapi/mpsguisync.hpp>
#include<hapi/mpsguivalue.hpp>
#include<hapi/mpsassign.hpp>
#include<hapi/mpshoststatement.hpp>
#include<hapi/mpshostheader.hpp>
